version: '2'
services:
        dockerapp:
                extends:
                        file: common.yml
                        service: dockerapp
                image: nad2000/dockerapp

        redis:
                extends:
                        file: common.yml
                        service: redis
